# Do not modify this file!  It was generated by 'nixos-generate-configuration'
# and will be overwritten on each 'nixos-rebuild switch'.
# To customize, create /etc/nixos/hardware-configuration.nix and replace
# this file, or set 'hardware-configuration' option in your host's system.nix.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
